In [330]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



data=pd.read_csv('cust_satisfaction.csv')
# print(data.count())
# print(data.duplicated())
print(data.nunique())  #for checking the unique values of the attributes in the dataframe data



Gender                           2
Customer Type                    2
Type of Travel                   2
Class                            3
satisfaction                     2
Age                             75
Flight Distance               3802
Inflight entertainment           6
Baggage handling                 5
Cleanliness                      6
Departure Delay in Minutes     446
Arrival Delay in Minutes       455
dtype: int64


In [331]:
print(data['Customer Type'].value_counts())
data.info()

Customer Type
Loyal Customer       84923
disloyal Customer    18981
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Gender                      103904 non-null  object 
 1   Customer Type               103904 non-null  object 
 2   Type of Travel              103904 non-null  object 
 3   Class                       103904 non-null  object 
 4   satisfaction                103904 non-null  object 
 5   Age                         103904 non-null  int64  
 6   Flight Distance             103904 non-null  int64  
 7   Inflight entertainment      103904 non-null  int64  
 8   Baggage handling            103904 non-null  int64  
 9   Cleanliness                 103904 non-null  int64  
 10  Departure Delay in Minutes  103904 non-null  int64  
 11  Arrival Delay in Minutes    103594 n

In [332]:
# print(data.isnull().sum())


# df=data.shape[0]-data.isnull()  #for removing the null values from the dataset
data.dropna(inplace=True)   #also can be done by this function dropna
print(data.isnull().sum())

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
satisfaction                  0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64


In [333]:
print(data.duplicated().sum())
data.drop_duplicates(inplace=True)  #for removing the duplicated data

print(data.duplicated().sum())


172
0


In [334]:
loyal_customer=data[data['Customer Type']=='Loyal Customer']  #storing the loyal_customer into the another data frame
disloyal_customer=data[data['Customer Type']=='disloyal Customer']  #storing the disloyal customer in the another data frame

# print(loyal_customer.count())
print(loyal_customer.head())
# print(disloyal_customer.count())
print(disloyal_customer.head())

   Gender   Customer Type   Type of Travel     Class             satisfaction  \
0    Male  Loyal Customer  Personal Travel  Eco Plus  neutral or dissatisfied   
2  Female  Loyal Customer  Business travel  Business                satisfied   
3  Female  Loyal Customer  Business travel  Business  neutral or dissatisfied   
4    Male  Loyal Customer  Business travel  Business                satisfied   
5  Female  Loyal Customer  Personal Travel       Eco  neutral or dissatisfied   

   Age  Flight Distance  Inflight entertainment  Baggage handling  \
0   13              460                       5                 4   
2   26             1142                       5                 4   
3   25              562                       2                 3   
4   61              214                       3                 4   
5   26             1180                       1                 4   

   Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  
0            5             

In [335]:
loyal_customer1=loyal_customer.sample(21000)
print(loyal_customer1.count())
loyal_customer1.shape

Gender                        21000
Customer Type                 21000
Type of Travel                21000
Class                         21000
satisfaction                  21000
Age                           21000
Flight Distance               21000
Inflight entertainment        21000
Baggage handling              21000
Cleanliness                   21000
Departure Delay in Minutes    21000
Arrival Delay in Minutes      21000
dtype: int64


(21000, 12)

In [336]:
balance_df=pd.concat([loyal_customer1,disloyal_customer],axis=0)
# print(balance_df.count())
print(balance_df.head())

       Gender   Customer Type   Type of Travel     Class  \
93692    Male  Loyal Customer  Business travel  Business   
53831  Female  Loyal Customer  Personal Travel       Eco   
39047    Male  Loyal Customer  Business travel  Business   
83024    Male  Loyal Customer  Personal Travel       Eco   
18119    Male  Loyal Customer  Personal Travel       Eco   

                  satisfaction  Age  Flight Distance  Inflight entertainment  \
93692                satisfied   55             1916                       4   
53831  neutral or dissatisfied   20              462                       1   
39047                satisfied   46             3966                       4   
83024  neutral or dissatisfied   40              406                       3   
18119  neutral or dissatisfied   19              862                       3   

       Baggage handling  Cleanliness  Departure Delay in Minutes  \
93692                 4            3                           0   
53831                 

In [337]:
cat_col=balance_df.select_dtypes(include='O')
num_col=balance_df.select_dtypes(exclude='O')
print(num_col.head())
print(cat_col.head())
print(num_col.shape)
print(cat_col.shape)

       Age  Flight Distance  Inflight entertainment  Baggage handling  \
93692   55             1916                       4                 4   
53831   20              462                       1                 5   
39047   46             3966                       4                 4   
83024   40              406                       3                 5   
18119   19              862                       3                 4   

       Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  
93692            3                           0                       0.0  
53831            1                           0                       0.0  
39047            5                           0                       0.0  
83024            3                           0                       0.0  
18119            3                         110                      97.0  
       Gender   Customer Type   Type of Travel     Class  \
93692    Male  Loyal Customer  Business travel  Bus

In [338]:
cat_col


Gender      Customer Type   Type of Travel     Class  \
93692     Male     Loyal Customer  Business travel  Business   
53831   Female     Loyal Customer  Personal Travel       Eco   
39047     Male     Loyal Customer  Business travel  Business   
83024     Male     Loyal Customer  Personal Travel       Eco   
18119     Male     Loyal Customer  Personal Travel       Eco   
...        ...                ...              ...       ...   
103892  Female  disloyal Customer  Business travel  Business   
103895  Female  disloyal Customer  Business travel       Eco   
103899  Female  disloyal Customer  Business travel       Eco   
103901    Male  disloyal Customer  Business travel  Business   
103902  Female  disloyal Customer  Business travel       Eco   

                   satisfaction  
93692                 satisfied  
53831   neutral or dissatisfied  
39047                 satisfied  
83024   neutral or dissatisfied  
18119   neutral or dissatisfied  
...                         ...  
103892  neutral or dissatisfied  
103895  neutral or dissatisfied  
103899  neutral or dissatisfied  
103901  neutral or dissatisfied  
103902  neutral or dissatisfied  

[39905 rows x 5 columns]

In [339]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


encoder=OneHotEncoder(drop='if_binary')


In [340]:
encoder=OneHotEncoder()

print(OneHotEncoder.__doc__)  #to printing the documentation of the OneHotEncoder class





    Encode categorical features as a one-hot numeric array.

    The input to this transformer should be an array-like of integers or
    strings, denoting the values taken on by categorical (discrete) features.
    The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
    encoding scheme. This creates a binary column for each category and
    returns a sparse matrix or dense array (depending on the ``sparse_output``
    parameter).

    By default, the encoder derives the categories based on the unique values
    in each feature. Alternatively, you can also specify the `categories`
    manually.

    This encoding is needed for feeding categorical data to many scikit-learn
    estimators, notably linear models and SVMs with the standard kernels.

    Note: a one-hot encoding of y labels should use a LabelBinarizer
    instead.

    Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
    For a comparison of different encoders, refer to:
    :ref:`sp

In [341]:
onehot_data=encoder.fit_transform(cat_col).toarray()
print(onehot_data.shape)
print(onehot_data)
print

(39905, 11)
[[0. 1. 1. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [342]:
column_names=list(encoder.get_feature_names_out())
column_names

['Gender_Female',
 'Gender_Male',
 'Customer Type_Loyal Customer',
 'Customer Type_disloyal Customer',
 'Type of Travel_Business travel',
 'Type of Travel_Personal Travel',
 'Class_Business',
 'Class_Eco',
 'Class_Eco Plus',
 'satisfaction_neutral or dissatisfied',
 'satisfaction_satisfied']

In [343]:
one_hot=pd.DataFrame(onehot_data,columns=column_names)

# print(one_hot.isnull().sum())

In [352]:
final_df=pd.concat([one_hot,num_col],axis=1)
print(final_df)



       Gender_Female  Gender_Male  Customer Type_Loyal Customer  \
0                0.0          1.0                           1.0   
1                1.0          0.0                           1.0   
2                0.0          1.0                           1.0   
3                0.0          1.0                           1.0   
4                0.0          1.0                           1.0   
...              ...          ...                           ...   
39900            1.0          0.0                           0.0   
39901            1.0          0.0                           0.0   
39902            1.0          0.0                           0.0   
39903            0.0          1.0                           0.0   
39904            1.0          0.0                           0.0   

       Customer Type_disloyal Customer  Type of Travel_Business travel  \
0                                  0.0                             1.0   
1                                  0.0         

In [353]:
num_col.reset_index(drop=True,inplace=True)
print(final_df)

       Gender_Female  Gender_Male  Customer Type_Loyal Customer  \
0                0.0          1.0                           1.0   
1                1.0          0.0                           1.0   
2                0.0          1.0                           1.0   
3                0.0          1.0                           1.0   
4                0.0          1.0                           1.0   
...              ...          ...                           ...   
39900            1.0          0.0                           0.0   
39901            1.0          0.0                           0.0   
39902            1.0          0.0                           0.0   
39903            0.0          1.0                           0.0   
39904            1.0          0.0                           0.0   

       Customer Type_disloyal Customer  Type of Travel_Business travel  \
0                                  0.0                             1.0   
1                                  0.0         

In [346]:
final_df.to_csv('cust_ariline_cleaned.csv',index=False)

In [347]:
x=final_df.drop('Customer Type_disloyal Customer',axis=1)

y=final_df['Customer Type_Loyal Customer']