# NUMPY

In [5]:
import numpy as np                  # used to immport numpy as np

In [5]:
lst = list(range(1,30))
arr1 = np.array(lst)                 # used to print array by passing list as argument.
arr1                                        

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
arr2 = np.arange(1,30)                  # in this we don't need list to pass.
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])         #  in this we just pass list in array.
arr3                                             # used for directly pass array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr4 = np.zeros((10))           # used to print zeros
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr5 = np.ones((10))                # used to print ones
arr5                            

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
a = np.zeros((5,10))            #used to print 2D array here 5 is row and is column
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
b = np.ones((4,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
arr6 = np.linspace(1,10,8)              # here 1 and 10 is a range and 8 is the number of element
arr6

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [19]:
arr7 = np.arange(0,30).reshape(10,3)
arr7                                # arange(0,30) is used to print array, and reshape(10,3) is used to print this array
                                    # in 10 column. ans 3 rows. 
                                    # and also used to convert 1D to 2D array.
                                                   

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [21]:
d = np.arange(0,60).reshape(12,5)           # in reshape we always takes the multiple of given array.
d                                               

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

## RANDOM NUMBERS ARRAY GENERATION

In [25]:
arr_1d = np.random.randint(1,5,9)    
arr_1d                                   # create random array in between 1 to 5 and give 9 element.

array([3, 4, 3, 3, 3, 2, 2, 4, 3])

In [27]:
arr_2d = np.random.randint(1,5,(5,2))
arr_2d                                        # create (5,2) array in range 1 to 5.
                                            # used to create 2D array  using random number.

array([[3, 4],
       [2, 2],
       [1, 4],
       [3, 3],
       [2, 1]])

In [32]:
d  = np.random.random(10)
d                                     # used to give random float value.

array([0.90419549, 0.59052451, 0.70062418, 0.27747147, 0.04745874,
       0.72209153, 0.98161257, 0.07950658, 0.96387565, 0.79640586])

In [34]:
d  = np.random.random((5,6))
d                                     # used to create 2D array.

array([[0.95552603, 0.46310765, 0.77247241, 0.9670243 , 0.72788114,
        0.98180244],
       [0.01875087, 0.36816588, 0.26244162, 0.17820968, 0.9427605 ,
        0.8163137 ],
       [0.8148843 , 0.71702879, 0.94461396, 0.63959058, 0.66273857,
        0.17814462],
       [0.45986695, 0.13790881, 0.29276208, 0.15939354, 0.94172989,
        0.33921922],
       [0.40559013, 0.1429646 , 0.26257392, 0.43985084, 0.87911986,
        0.19530307]])

### Array Attributes

In [35]:
arr = np.arange(0,60).reshape(10,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [36]:
arr.shape           # return shape of array

(10, 6)

In [37]:
arr.dtype           # return the type of array

dtype('int32')

In [38]:
arr.ndim          # return dimension  of array

2

In [39]:
arr.size            # return the size of array

60

In [40]:
arr.flatten()          #convert 2D to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
arr.ravel()             # also used to convert 2D to 1D.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [45]:
lst1 = [[1,2,3],[4,5,6]]
lst1                                            # making 2D array from list.
arr = np.array(lst1)                            # the number of element in list should be equal.
arr                                             

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr.shape

(2, 3)

In [47]:
arr.T                   # used to print the transpose of matrix.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
arr.T.shape               # used to print the shape of transpose matrix.

(3, 2)

### Acessing element from 1D and 2D array

for 1d array -
[row_start : end : step/skip]

for 2d array  -
[row_start: end : skip/step : column_strat : end : skip/step ]

In [50]:
z = np.arange(0,60)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [54]:
z[25]

25

In [56]:
z[21:26]

array([21, 22, 23, 24, 25])

In [57]:
z[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 2D array

In [58]:
y = np.arange(60).reshape(12,5)
y


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [59]:
y[1][3]         # used to print single element

8

In [60]:
y[2]            # used to print a row

array([10, 11, 12, 13, 14])

In [62]:
y[0:2,0:2]          # used to print matrix

array([[0, 1],
       [5, 6]])

In [63]:
y[0:13,0:1]         # it will print first column

array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50],
       [55]])

In [64]:
y[1,3:5]

array([8, 9])

In [65]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [68]:
y[7:8,4]

array([39])

In [69]:
y[7:8,4][0]=100             # [0] is used to remove array
y

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [70]:
y[7,4]

100

In [71]:
y[11][-1]

59

In [73]:
y[-1][-1]

59

In [74]:
y[-1][4]

59

In [75]:
y[11:,-1]

array([59])

In [76]:
y[11:,-1][0]

59

In [77]:
y[11,4]

59

### For 3D array

In [6]:
import numpy as np
arr = np.array(np.arange(225).reshape(5,15,3))
arr                                         # 15 is row , 3 is column , 5 is tables

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [80]:
arr.shape           #[table,row,column]  --> for 3D array

(5, 15, 3)

In [7]:
arr[0][2:]          # zeroth table m se 2nd column se print kiya h

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [9]:
arr[:,0,:]      #access zeroth row of every table

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [10]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [11]:
arr[:,1:2,1:2]

array([[[  4]],

       [[ 49]],

       [[ 94]],

       [[139]],

       [[184]]])

In [12]:
arr[2][3][1]

100

In [13]:
arr[2][3][1]=500

In [15]:
arr[2][3][1]=100

In [16]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [7]:
import numpy as np

In [8]:

arr[0][::-1]  
           #reversing the row

NameError: name 'arr' is not defined

In [20]:
arr[0][::-1,::-1]

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])